baseurl = "https://jimmysong.io/"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh-cn"
title = "Jimmy Song" 
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
hello = "Hi,我是宋净超"
subtitle = "ArchSummit2017北京站见！9:30 am Dec 9, Sat, Meetring Room 5"
logo = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/avatar-icon.png"
favicon = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/favicon.ico"
dateFormat = "January 2, 2006"
commit = false
#rss = true
comments = true
#sharebutton = true
algolia = "d2134c5a8d250e6d3246594240c45201" # API key
#gcse = "012737790962522169780:fd1izxsfgrs" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
description = "jimmysong.io|宋净超的博客|Cloud Native|Big Data"
errorpage = "https://res.cloudinary.com/jimmysong/image/upload/images/404-not-found-cat.png"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/images/beijing-national-conversation-center.jpg"
desc = "北京国家会议中心"

#[[Params.bigimg]]
#src = "https://res.cloudinary.com/jimmysong/image/upload/banners/keuc-cncf.jpg"
#desc = "KEUC - China Kubernetes End User Conference 2017"
#
#[[Params.bigimg]]
#src = "https://res.cloudinary.com/jimmysong/image/upload/banners/cloud-computing.jpg"
#desc = "Cloud Computing for every one"
#
#[[Params.bigimg]]
#src = "https://res.cloudinary.com/jimmysong/image/upload/banners/great-wall-01.jpg"
#desc = "Cross the Great Wall to the world"
#
#[[Params.bigimg]]
#src = "https://res.cloudinary.com/jimmysong/image/upload/banners/big-data-1.jpg"
#desc = "Big Data for business decision"
#
#[[Params.bigimg]]
#src = "https://res.cloudinary.com/jimmysong/image/upload/banners/data-science-1.jpg"
#desc = "Data Science for complexity of human society"

[Author]
  name = "Jimmy Song"
 # website = "https://jimmysong.io"
  email = "rootsongjc@gmail.com"
  facebook = "jimmysongio"
 # googleplus = "+jimmysong" # or xxxxxxxxxxxxxxxxxxxxx
  github = "rootsongjc"
  twitter = "jimmysongio"
  linkedin = "jimmysongio"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 1
    
[[menu.main]]
    parent = "Categories"
    name = "Cloud Native"
    url = "categories/cloud-native"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "Microservices"
    url = "categories/microservices"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Devops"
    url = "categories/devops"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Github"
    url = "categories/github"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Docker"
    url = "categories/docker"
    weight = 6

[[menu.main]]
    parent = "Categories"
    name = "Code"
    url = "categories/code"
    weight = 7

[[menu.main]]
    parent = "Categories"
    name = "Tags"
    url = "tags"
    weight = 8

[[menu.main]]
    identifier = "Books"
    name = "Books"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Go"
    url = "cloud-native-go"
    weight = 1

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Python"
    url = "posts/cloud-native-python"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Kubernetes handbook"
    url = "kubernetes-handbook"
    weight = 3

[[menu.main]]
    parent = "Books"
    name = "Docker handbook"
    url = "docker-handbook"
    weight = 4

[[menu.main]]
    parent = "Books"
    name = "Hugo Handbook"
    url = "hugo-handbook"
    weight = 5

[[menu.main]]
    parent = "Books"
    name = "Istio service mesh"
    url = "http://istio.doczh.cn"
    weight = 6

[[menu.main]]
    parent = "Books"
    name = "Migrating to Cloud Native"
    url = "migrating-to-cloud-native-application-architectures"
    weight = 7

[[menu.main]]
    identifier = "Projects"
    name = "Projects"
    weight = 3

[[menu.main]]
    parent = "Projects"
    name = "Spark on kubernetes"
    url = "spark-on-k8s"
    weight = 1

[[menu.main]]
    parent = "Projects"
    name = "Awesome Cloud Native"
    url = "awesome-cloud-native"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "Cloudinary go"
    url = "posts/cloudinary-go"
    weight = 3

[[menu.main]]
    parent = "Projects"
    name = "Magpie"
    url = "posts/yarn-on-docker"
    weight = 4

[[menu.main]]
    parent = "Projects"
    name = "Cheatsheets"
    url = "cheatsheets"
    weight = 5

[[menu.main]]
    name = "About"
    url = "about"
    weight = 4
