languageCode = "zh-hans"
title = "Jimmy Song - Focus on Big Data & Cloud Native"
baseurl = "https://jimmysong.io/"
disqusShortname = "rootsongjc"
hasCJKLanguage = true
pygmentsuseclasses = true
PygmentsCodeFences = true
PygmentsStyle = "default"
