######################## default configuration ####################
baseURL = "https://jimmysong.io"
title = "Jimmy Song's blog"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "100"
metaDataFormat = "yaml"
hasCJKLanguage = true
DefaultContentLanguage = "zh"
gcs_engine_id="012737790962522169780:fd1izxsfgrs"
# disable language
disableLanguages = [] # desable language from here
pygmentsUseClasses=true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "permalink", "image","description"]
params = ["tags","categories"]

[params.repository]
url = "https://github.com/rootsongjc/website"
branch = "master"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/hightlight/syntax.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/tocbot/tocbot.css"


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/bigpicture/bigpicture.min.js"
[[params.plugins.js]]
link = "plugins/hex_md5/hex_md5.js"
[[params.plugins.js]]
link = "plugins/anchor/anchor.min.js"
[[params.plugins.js]]
link = "plugins/tocbot/tocbot.min.js"

#################### default parameters ################################
[params]
logo = "images/logo.svg"
# Meta data
description = "å®‹å‡€è¶…ï¼ˆJimmy Songï¼‰çš„ä¸ªäººåšå®¢ï¼Œ ä¸“æ³¨äºæ¢ç´¢å Kubernetes æ—¶ä»£çš„äº‘åŸç”Ÿæ–°èŒƒå¼ã€‚"
author = "Jimmy Song"
# contact info
address = "Beijing, China"
email = "jimmysong@jimmysong.io"
wechat = "jimmysongio"
# contact form action
contact_form_action = "https://formspree.io/mpzdzdbj" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-93485976-1" # your id
# Baidu tongji
baidu_key = "11f7d254cfa4e0ca44b175c66d379ecc"
#search = true
enableComment = true
enableAdSense = false
anchored = true # add anchor on each head title in the blog article content
code_copy_button = true
back_to_top_button = true


# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
#[params.subscription]
#enable = true
# mailchimp subsciption
#mailchimp_form_action = "https://jimmysong.us20.list-manage.com/subscribe/post?u=cca519d8764547a389f52c57f&amp;id=e8e9e07dcc"
# Use RSS instead
#mailchimp_form_name = "b_cca519d8764547a389f52c57f_e8e9e07dcc"

# Ads
[params.ad]
enable= false
image = "images/jksj.jpg"
url = "https://time.geekbang.org/column/intro/100015201?tab=catalog&code=IRLmmVKgTghcFr5iafwl9kZezb48Uhf4Pjdf13-W3ko%3D"
title = "æ·±å…¥å‰–æ Kubernetes"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social site ########################
[[params.social]]
title = "twitter"
icon = "fa-twitter"
link = "https://twitter.com/jimmysongio"

#[[params.social]]
#title = "youtube"
#icon = "fa-youtube"
#link = "https://www.youtube.com/channel/UCwLGlxo3b492bzIgD8lnOKg/"

[[params.social]]
title = "github"
icon = "fa-github"
link = "https://github.com/rootsongjc"

[[params.social]]
title = "linkedin"
icon = "fa-linkedin"
link = "https://linkedin.com/in/jimmysongio"

[[params.social]]
title = "mail"
icon = "fa-envelope"
link = "mailto:jimmysong@jimmysong.io"

[[params.social]]
title = "RSS"
icon = "fa-rss"
link = "/blog/index.xml"

################################### English language #####################################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
home = "Home"
# copyright
copyright = "&copy; 2017-2022 Jimmy Song All Right Reserved"

# top header
top_header = false
top_header_content = ""

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 2

[[menu.main]]
name = "Book"
URL = "https://lib.jimmysong.io"
weight = 3

[[menu.main]]
name = "Event"
URL = "https://lib.jimmysong.io/event/"
weight = 4

[[menu.main]]
name = "Notice"
URL = "notice"
weight = 5

[[menu.main]]
name = "Tags"
URL = "tags"
weight = 6

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 7

# footer links

[[menu.footer]]
name = "Tetrate Istio Distro"
URL = "https://istio.tetratelabs.io/"

[[menu.footer]]
name = "Cloud Native Community(China)"
URL = "https://cloudnative.to"

[[menu.footer]]
name = "Awesome Cloud Native"
URL = "/awesome-cloud-native/"

[[menu.footer]]
name = "Jimmy's YouTube Channel"
URL = "https://www.youtube.com/channel/UCwLGlxo3b492bzIgD8lnOKg/"

[[menu.footer]]
name = "Tetrate - Service Mesh Company"
URL = "https://tetrate.io/?jimmysong"

# book

[[menu.book]]
name = "Kubernetes Handbook"
URL = "https://lib.jimmysong.io/kubernetes-handbook/"

[[menu.book]]
name = "Istio Handbook"
URL = "https://lib.jimmysong.io/istio-handbook/"

[[menu.book]]
name = "Envoy Handbook"
URL = "https://lib.jimmysong.io/envoy-handbook/"

[[menu.book]]
name = "Cloud Native Bible"
URL = "https://lib.jimmysong.io/cloud-native/"

################################### Chinese language #####################################
[Languages.zh]
languageName = "ä¸­æ–‡"
languageCode = "zh"
contentDir = "content/zh"
home = "ä¸»é¡µ"
title = "Jimmy Song - ä¸“æ³¨äºæ¢ç´¢å Kubernetes æ—¶ä»£çš„äº‘åŸç”Ÿæ–°èŒƒå¼"
# copyright
copyright = "&copy; 2017-2022 Jimmy Song ä¿ç•™æ‰€æœ‰æƒåˆ©"
# top header
top_header = true
top_header_content = "ğŸ“£ äº‘åŸç”Ÿç¤¾åŒºè‘—çš„ã€Šæ·±å…¥ç†è§£ Istioã€‹å‡ºç‰ˆå•¦ï¼Œ[å‰å¾€è´­ä¹°](https://item.jd.com/13200745.html)"

# main menu
[[Languages.zh.menu.main]]
name = "åšå®¢"
URL = "blog"
weight = 2

[[Languages.zh.menu.main]]
name = "å›¾ä¹¦"
URL = "https://lib.jimmysong.io/"
weight = 3

[[Languages.zh.menu.main]]
name = "è¯‘æ–‡"
URL = "https://lib.jimmysong.io/blog/"
weight = 4

[[Languages.zh.menu.main]]
name = "ç¤¾åŒº"
URL = "https://cloudnative.to"
weight = 5

[[Languages.zh.menu.main]]
name = "æ´»åŠ¨"
URL = "https://lib.jimmysong.io/event/"
weight = 6

[[Languages.zh.menu.main]]
name = "æ ‡ç­¾"
URL = "tags"
weight = 7

[[Languages.zh.menu.main]]
name = "è”ç³»"
URL = "contact"
weight = 8

[[Languages.zh.menu.main]]
name = "é€šçŸ¥"
URL = "notice"
weight = 9

[[Languages.zh.menu.main]]
name = "å…³äº"
URL = "about"
weight = 10

[[Languages.zh.menu.footer]]
name = "äº‘åŸç”Ÿå¼€æºé¡¹ç›®å¤§å…¨"
URL = "https://jimmysong.io/awesome-cloud-native/"

[[Languages.zh.menu.footer]]
name = "äº‘åŸç”Ÿå­¦é™¢|Bilibili"
URL = "https://space.bilibili.com/515485124"

[[Languages.zh.menu.footer]]
name = "äº‘åŸç”Ÿèµ„æ–™åº“"
URL = "https://lib.jimmysong.io"

[[Languages.zh.menu.footer]]
name = "äº‘åŸç”Ÿç¤¾åŒºï¼ˆä¸­å›½ï¼‰"
URL = "https://cloudnative.to"

[[Languages.zh.menu.footer]]
name = "Tetrate å…¬å¸"
URL = "https://tetrate.io/?jimmysong"

# book

[[Languages.zh.menu.book]]
name = "Kubernetes åŸºç¡€æ•™ç¨‹"
URL = "https://lib.jimmysong.io/kubernetes-handbook/"

[[Languages.zh.menu.book]]
name = "Istio åŸºç¡€æ•™ç¨‹"
URL = "https://lib.jimmysong.io/istio-handbook/"

[[Languages.zh.menu.book]]
name = "Envoy åŸºç¡€æ•™ç¨‹"
URL = "https://lib.jimmysong.io/envoy-handbook/"

[[Languages.zh.menu.book]]
name = "æ·±å…¥ç†è§£ Istio"
URL = "/blog/istio-service-mesh-book/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
