######################## default configuration ####################
baseURL = "https://jimmysong.io"
title = "Jimmy Song - Cloud Native | Open Source | Community"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "6"
metaDataFormat = "yaml"
hasCJKLanguage = true
DefaultContentLanguage = "zh"
gcs_engine_id="012737790962522169780:fd1izxsfgrs"
# disqus short name
#disqusShortname = "jimmysong" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
pygmentsUseClasses=true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/hightlight/syntax.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/bigPicture/bigPicture.js"
[[params.plugins.js]]
link = "plugins/hex_md5/hex_md5.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Jimmy Song's Blog"
author = "Jimmy Song"
# contact info
address = "Beijing, China"
email = "jimmysong@jimmysong.io"
wechat = "jimmysongio"
wechatCode = "/images/jimmysong-wechat-qr-code.jpg"
twitterCode = "/images/jimmysong-wechat-qr-code.jpg"
# contact form action
contact_form_action = "https://formspree.io/mpzdzdbj" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-93485976-1" # your id
# Baidu tongji
baidu_key = "11f7d254cfa4e0ca44b175c66d379ecc"
# top header
top_header = false
search = true
# Gitalk
enableGitalk = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
#mailchimp_form_action = "https://jimmysong.us20.list-manage.com/subscribe/post?u=cca519d8764547a389f52c57f&amp;id=e8e9e07dcc"
# Use RSS instead
mailchimp_form_action = "/blog/index.xml"
mailchimp_form_name = "b_cca519d8764547a389f52c57f_e8e9e07dcc"

# Ads
[params.ad]
enable= false
image = "images/mosn-banner.png"
url = "https://mosn.io"
title = "MOSN - 蚂蚁集团开源的云原生网络代理"

[params.gitalk]
clientID = "93a0df08e0f93ff0c8a3" # Your client ID
clientSecret = "89f20e962982401489bc9339dea437161ea44c68" # Your client secret
repo = "rootsongjc.github.io" # The repo to store comments
owner = "rootsongjc" # Your GitHub ID
admin= "rootsongjc" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
id= "location.pathname" # The unique id of the page.
labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
perPage= 15 # Pagination size, with maximum 100.
pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social site ########################
[[params.social]]
title = "twitter"
icon = "fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/jimmysongio"

[[params.social]]
title = "facebook"
icon = "fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://facebook.com/jimmysongio"

[[params.social]]
title = "github"
icon = "fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/rootsongjc"

[[params.social]]
title = "linkedin"
icon = "fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://linkedin.com/in/jimmysongio"

[[params.social]]
title = "RSS"
icon = "fa-rss" # themify icon : https://themify.me/themify-icons
link = "/blog/index.xml"

################################### English language #####################################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 Jimmy Song All Right Reserved;</br> Powerd by Hugo with [educenter](https://github.com/themefisher/educenter-hugo) theme"

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Book"
URL = "book"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Partner"
URL = "partner"
weight = 4

[[menu.main]]
name = "Notice"
URL = "notice"
weight = 5

[[menu.main]]
name = "Event"
URL = "event"
weight = 6

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 7

# footer menu

[[menu.footer]]
name = "Partner"
URL = "/partner"

[[menu.footer]]
name = "Event"
URL = "/event"

[[menu.footer]]
name = "Notice"
URL = "/notice"

[[menu.footer]]
name = "Awesome Cloud Native"
URL = "/awesome-cloud-native"

[[menu.footer]]
name = "MosnProxy"
URL = "https://mosn.io"

################################### Chinese language #####################################
[Languages.zh]
languageName = "中文"
languageCode = "zh"
contentDir = "content/zh"
home = "主页"
# copyright
copyright = "Copyright &copy; 2020 Jimmy Song 保留所有权利；</br>基于 Hugo [educenter](https://github.com/themefisher/educenter-hugo)  主题构建"

# main menu
[[Languages.zh.menu.main]]
name = "关于"
URL = "about"
weight = 1

[[Languages.zh.menu.main]]
name = "图书"
URL = "book"
weight = 2

[[Languages.zh.menu.main]]
name = "博客"
URL = "blog"
weight = 3

[[Languages.zh.menu.main]]
parent = "博客"
name = "容器"
URL = "/categories/容器"
weight = 1

[[Languages.zh.menu.main]]
parent = "博客"
name = "Kubernetes"
URL = "/categories/kubernetes"
weight = 2

[[Languages.zh.menu.main]]
parent = "博客"
name = "service mesh"
URL = "/categories/service-mesh"
weight = 3

[[Languages.zh.menu.main]]
parent = "博客"
name = "云原生"
URL = "/categories/云原生"
weight = 4

[[Languages.zh.menu.main]]
parent = "博客"
name = "开源"
URL = "/categories/开源"
weight = 5

[[Languages.zh.menu.main]]
parent = "博客"
name = "其他"
URL = "/categories/其他"
weight = 6

[[Languages.zh.menu.main]]
parent = "博客"
name = "所有"
URL = "/blog"
weight = 7

[[Languages.zh.menu.main]]
name = "社区"
URL = "community"
weight = 4

[[Languages.zh.menu.main]]
parent = "社区"
name = "云原生社区"
URL = "https://cloudnative.to"
weight = 1

[[Languages.zh.menu.main]]
parent = "社区"
name = "服务网格社区"
URL = "https://wwww.servicemesher.com"
weight = 2

[[Languages.zh.menu.main]]
name = "联系"
URL = "contact"
weight = 5

[[Languages.zh.menu.main]]
name = "更多"
weight = 7

[[Languages.zh.menu.main]]
parent = "更多"
name = "伙伴"
URL = "partner"
weight = 1

[[Languages.zh.menu.main]]
parent = "更多"
name = "通知"
URL = "notice"
weight = 2

[[Languages.zh.menu.main]]
parent = "更多"
name = "活动"
URL = "event"
weight = 3

[[Languages.zh.menu.main]]
parent = "更多"
name = "招聘"
URL = "job"
weight = 4

# footer menu

[[Languages.zh.menu.footer]]
name = "Awesome Cloud Native"
URL = "/awesome-cloud-native"

[[Languages.zh.menu.footer]]
name = "云原生网络代理 MOSN"
URL = "https://mosn.io"

[[Languages.zh.menu.footer]]
name = "SOFAStack"
URL = "https://www.sofastack.tech"

[[Languages.zh.menu.footer]]
name = "ServiceMesher"
URL = "https://www.servicemesher.com"

[[Languages.zh.menu.footer]]
name = "云原生社区"
URL = "https://cloudnative.to"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
